name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configura chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy para EC2
        run: |
          ssh -T -i ~/.ssh/id_rsa ubuntu@3.133.132.217 << 'EOF'
            cd ~/validacao-cliente
            git pull origin main
            ./mvnw clean package -DskipTests
            pkill -f 'java -jar' || true
            nohup java -jar target/*.jar > app.log 2>&1 &
          EOF

